// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vodcljbskbxiihxilrwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvZGNsamJza2J4aWloeGlscndhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTg5NTMsImV4cCI6MjA3NDIzNDk1M30.SOsztg0rhhfFxTfNdvGlfHkPLbQtEu929db0AvWbxqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});